### ISSUE TITLE
hangs at the base (the returns)

### ISSUE THREAD

**Issue by rinnocenti** [ernieayala/ernies-modern-layout#10]
it's better but it still happens.

I try reproduce and i found a way.
1 - to compendium open a Item.
2 - Minimize the item window
3 - Drag & drop the minimized window to left (* it will open, maybe a bug *, minimize again)
4 - open a new item from compendium, and enter in "details" (or other option who enlarge the window at bottom like "file pick")
the window now fix in bottom.

other steps cause the bug eather (how to have more than one window minimized and open a new one, however the bug does not always appear like this but it happens.)

**Comment by ernieayala** [comment]
@rinnocenti I think I found the issue with this. I had a max-height on the window and for some reason it would act weird. I moved shuffled some stuff around and I think that fixed the issue. Well at least the way you described. 

Also the window getting bigger after dragging it seems to be a foundry bug

**Comment by rinnocenti** [comment]
I really appreciate your attention and dedication

**Comment by ernieayala** [comment]
No problem. Gonna close the issue. If it happens again... well... guess I'll have to work on it agian. haha
