### ISSUE TITLE
No visual indication of rolling a nat 1 or nat 20

### ISSUE THREAD

**Issue by InfamousPlanet** [ernieayala/ernies-modern-layout#101]
The rolled numbers dont turn red or green with crits
![Untitled](https://user-images.githubusercontent.com/83744909/122670107-23d0b480-d1b8-11eb-9eb2-09acd9901985.png)
![Untitled2](https://user-images.githubusercontent.com/83744909/122670110-24694b00-d1b8-11eb-885d-53c9680ef520.png)

**Comment by ernieayala** [comment]
Good catch. Felt there was something missing when I was running my game.
