### ISSUE TITLE
EMUI changes text colour on FATE Official character sheets, making them unreadable

### ISSUE THREAD

**Issue by zorhold** [ernieayala/ernies-modern-layout#105]
Hey, I've encountered difficulties with Modern UI and the FATE Official character sheets: Apparently, EMUI changes the font colour of the sheets, but doesn't change anything else, resulting in white font on light background.

_Character sheets with EMUI not active:_
![Character_Layout_no_UI_active](https://user-images.githubusercontent.com/86226697/122728657-a4ef8080-d278-11eb-871b-58fc6b52193d.png)

_Character sheets with EMUI active:_
![Character_Layout_UI_active](https://user-images.githubusercontent.com/86226697/122728786-c18bb880-d278-11eb-879c-f63cc5c203a4.png)

It doesn't affect all parts of the writing, but it does affect almost everything that's important. Changing the "Text colour - Standard" fixes the sheets but ruins everything else everywhere. Can you help me with the issue?

Cheers!

**Comment by ernieayala** [comment]
@zorhold Would you happen to have a used World you could send to me? It would really help me out in identifying the issues.

**Comment by zorhold** [comment]
Sure! Would you need the entire world folder? I can send it to you via DM.

**Comment by ernieayala** [comment]
@zorhold Just wanted to give you an update on this. This is turning out to be extremely difficult. There is an absurd amount of styles that are inline or have !important tags requiring me to create stupid amounts of specificity. There are no blanket changes so individual items have to be targeted. In the end - I can get something like 50% there but in the end - it requires the system itself to use CSS better.

**Comment by zorhold** [comment]
Yeah, I've seen your beta build and looked into it myself. Don't worry about it, it's not like it's an absolute necessity. You did a great job with what you achieved up to now!

**Comment by zorhold** [comment]
Checked out the update! Holy crap, you did an amazing job! Great work man, thanks!
