### ISSUE TITLE
Macro Title 

### ISSUE THREAD

**Issue by Akmenus** [ernieayala/ernies-modern-layout#107]
I don't know it's issue or not but belive valided post anyway.
I when use ernies layout , and roll in chat with macro, the name show left.
It's right?
Because name top is better i think. 
No active
![image](https://user-images.githubusercontent.com/75502446/122917165-17716680-d334-11eb-8c96-48f478144860.png)
Active
![image](https://user-images.githubusercontent.com/75502446/122917237-3112ae00-d334-11eb-985f-a6575390b8fc.png)

**Comment by ernieayala** [comment]
Yeah, that looks broken. What system are you on?

**Comment by Akmenus** [comment]
Simple World Build

**Comment by ernieayala** [comment]
@Akmenus Can you send me the macro script? I'm  having trouble replicating.

**Comment by Akmenus** [comment]
Sure, here:

```
let actorD = canvas.tokens.controlled[0]?.actor || game.user.character;
let first_content = `<p><b>Damage</b></p><form><div class="form-group"><input type="number" id="first_thing"></div></form>`;

new Dialog({
        title: "Damage",
        content: first_content,
        buttons: {
        go: { label: "Roll", callback: async (html) => {
            let first = html.find('#first_thing').val();
           new Roll(`1d20 + @tou - (${first}+15)`, actorD.getRollData()).roll().toMessage({
               flavor:`<b><h1>Resistência Dano</h1></b><br><h3>Sucesso (0 ou +) = No effect<br>1º = Resist <br>2º= Tont <br>3º= AR<br>4º = ...</h3>`, user: game.user._id, speaker: ChatMessage.getSpeaker({token: actor})}); 
        } }
                }
}).render(true);

```
You need a sheet actor and create attribute called tou.

![image](https://user-images.githubusercontent.com/75502446/123022950-f26d0a00-d3ac-11eb-8ce0-63a91d39ae1b.png)
