### ISSUE TITLE
DAE edit window's layout is not ideal

### ISSUE THREAD

**Issue by dirusulixes** [ernieayala/ernies-modern-layout#114]
FVTT 0.8.8
Ernie's 0.3.8
DAE 0.8.23

The alignment of the headers and the size of the fields in the DAE edit window are off
![image](https://user-images.githubusercontent.com/5693623/123495333-38c7a080-d61b-11eb-8d25-66bf87738f9c.png)

**Comment by ernieayala** [comment]
@dirusulixes I'm sure there are minor changes I can do on my end to help - though this thing built kinda funky. The headers are given static width values but the children rows are not.

![Capture](https://user-images.githubusercontent.com/9342233/123686024-2f4d5c80-d804-11eb-8f3f-2dbc3067af5d.JPG)
