### ISSUE TITLE
[Enhancement] Scenes bar show permission

### ISSUE THREAD

**Issue by LordOHelmet** [ernieayala/ernies-modern-layout#116]
The Foundry default for the scenes navigation bar looks like this:

![scenes](https://user-images.githubusercontent.com/80178910/123635907-84956800-d81c-11eb-9fe7-f2d9e6b3d69f.JPG)

The colour coding makes it easy to distinguish which scenes are accessible to the players (grey) and which aren't (blue).

The module makes it impossible to make this distinction:

![scenes mod](https://user-images.githubusercontent.com/80178910/123636518-43518800-d81d-11eb-83d9-eac0d7c560a1.JPG)

**Comment by ernieayala** [comment]
Seems like an oversight in my part. I'll add this in my next release.
