### ISSUE TITLE
playlist problem

### ISSUE THREAD

**Issue by zeteticl** [ernieayala/ernies-modern-layout#119]
![image](https://user-images.githubusercontent.com/23254376/124114252-efee6c80-da9e-11eb-938e-d43ef43f06c5.png)
![image](https://user-images.githubusercontent.com/23254376/124114372-0f859500-da9f-11eb-8213-2375c1b02e87.png)

SYSTEM: FVTT 0.8.8
WORLD: Call of cthulhu 0.6.0

![image](https://user-images.githubusercontent.com/23254376/124114780-90dd2780-da9f-11eb-983a-4a4fa626499f.png)
![image](https://user-images.githubusercontent.com/23254376/124114807-99356280-da9f-11eb-8a06-fb37bc378018.png)

**Comment by ernieayala** [comment]
Looks like CoC7 system css adds a width of 100% to those containers. I'll add an override on my side.
