### ISSUE TITLE
Ability to turn of different sections

### ISSUE THREAD

**Issue by datdamnzotz** [ernieayala/ernies-modern-layout#12]
There are some features that get hidden, like thumbs on the maps.
Would be nice to be able to turn that off and on.

![image](https://user-images.githubusercontent.com/3913859/87121433-f6f1ee80-c23f-11ea-8856-5674d9b1e427.png)

**Comment by ernieayala** [comment]
I'll add a toggle for that.

**Comment by ernieayala** [comment]
Added in https://github.com/ernieayala/ernies-modern-layout/releases/tag/0.1.3
