### ISSUE TITLE
Incompatibility with D&D5E Helpers module

### ISSUE THREAD

**Issue by roi007leaf** [ernieayala/ernies-modern-layout#122]
![image](https://user-images.githubusercontent.com/17231451/124416825-856c5380-dd60-11eb-876d-09e07b8b33d4.png)
cover system doesnt look right... right?

**Comment by ernieayala** [comment]
Can you give me a step to reproduce? I have no idea how to use this mod.

**Comment by giogreymon** [comment]
For DnD5e Helpers: turn on Automatic Cover (like in the 1st image), have a token target another token, chat should pop out like the 2nd image.
For Ernie's Modern UI: have Ernie's Layout turned ON.

![image](https://user-images.githubusercontent.com/77355668/125703710-9ace1857-ae0a-46f4-864f-1de12b37578b.png)

This is what it looks like when Ernie's Layout is ON.
![image](https://user-images.githubusercontent.com/77355668/125703774-0a6488e2-406f-44a6-a0c4-b272e59965cf.png)

This is what it looks like when Ernie's Layout is OFF.
![image](https://user-images.githubusercontent.com/77355668/125703933-ec024a74-b0be-4154-ba02-f53291c4e6e2.png)
