### ISSUE TITLE
Possible incompatibility with Theatre Inserts: Pause text and animation

### ISSUE THREAD

**Issue by dirusulixes** [ernieayala/ernies-modern-layout#124]
fvtt 0.8.8
Theatre inserts 1.17.0
Ernie's Modern UI 0.3.9

When both modules are enabled, the 'Game paused' text is moved way above the pause animation. No errors in the console. Neither of the modules alone shows the issue. see https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/issues/40

![image](https://user-images.githubusercontent.com/5693623/124517898-1123c580-dddd-11eb-8fda-ef483831046e.png)

**Comment by ernieayala** [comment]
Added some overrides to override their overrides for the pause. Overall the mod still is ugly with my mod turned on but it's functional.

**Comment by dirusulixes** [comment]
for my understanding, is this the override you are overriding: 
https://github.com/League-of-Foundry-Developers/fvtt-module-theatre/blob/2157fe75e5b635a7873dd0f6f5e4bdf775d2a9ea/app/css/theatre.css#L1404

**Comment by ernieayala** [comment]
yup - that's the one
