### ISSUE TITLE
Request to have the Starfinder game sheet work with theming

### ISSUE THREAD

**Issue by Yoonki1** [ernieayala/ernies-modern-layout#126]
Hello. I've messaged you about this and would like you to make the Starfinder game sheet work with the theming of your module. Specifically changing the color of the bars and texts on the sheet.

Thank you!

https://cdn.discordapp.com/attachments/862828920800935954/862830215016480788/unknown.png
https://cdn.discordapp.com/attachments/862828920800935954/862830225129996299/unknown.png

**Comment by ernieayala** [comment]
Likely will never get around to this. I exclude Actors and Items from my styling.
