### ISSUE TITLE
Several Ernie's Layout UI Errors

### ISSUE THREAD

**Issue by ghost** [ernieayala/ernies-modern-layout#128]
I've found several different instances where the UI screws up while Ernie's Layout is enabled. I tested them with and without compact mode on, just to see if it made a difference, and while it can make some of them _slightly_ worse, it's definitely Ernie's Layout that's causing the problems.

The first one I'll show is the compendium directory. The first image is how it looks without ernie's layout enabled, the second image is how it looks with ernie's layout enabled (notice some weird misaligned boxes at the very bottom with the compendium mapper mod), and the third one is what it looks like with ernies layout and compendium folders active, where the top and bottom buttons kinda break.
![Untitled-1](https://user-images.githubusercontent.com/83744909/125709882-e8ab3f41-9d24-4d97-8c4a-353bc4af404f.jpg)

The second is dialog windows, mostly ones created by macros, but I dont have many ways to create dialog windows, so it;';sh ard to test. Here's the Pathfinder 2e Treat Wounds macro without ernies layout enabled.
![Untitled-3](https://user-images.githubusercontent.com/83744909/125710535-6471f782-531c-4430-9f47-5cdac01439c0.jpg)
And here it is with ernies layout enabled.
![Animation1](https://user-images.githubusercontent.com/83744909/125710553-9ab36744-4991-40f7-9e7a-ac0b9b56c3f2.gif)

This last one might be related to the same thing that causes issues with dialog windows, but I'll put it in anyway just to be sure. This one happens when I open the window for the tooltip manager for Token Tooltip Alt. The images on the left are what happen when I open it with ernies layout disabled, and the images on the right are with ernies layout enabled.
![Untitled-4](https://user-images.githubusercontent.com/83744909/125710811-f3129404-932c-4925-aef4-010956e3a059.jpg)

**Comment by JoshDread** [comment]
Layout issue found in Manage Modules, it may be due to TidyUI but that was present in v8.9 where the issue was not present. Manage Module Window now is marginally too small, meaning an extra scroll bar has been added to the window in order to reach the confirm and reset buttons.

![image](https://user-images.githubusercontent.com/99120529/152677089-c6ae60f0-3e68-43ed-b83b-4c1ce698b380.png)
