### ISSUE TITLE
Monster Blocks Compatibility

### ISSUE THREAD

**Issue by Cubius** [ernieayala/ernies-modern-layout#130]
Compatibility with Monster Blocks would be greatly appreciated.
Two specific issues I found are:

- The background of the sheet is redefined, but some of the menu retains its styling.
![image](https://user-images.githubusercontent.com/15717384/126147486-90729d35-6aa3-4c1f-8071-c07ffe246cc5.png)
- When stat-blocks get too long, the sheet will automatically continue in a new column, this breaks entirely. The top section retains the correct behaviour but the bottom just displays as a single column underneath that.
![image](https://user-images.githubusercontent.com/15717384/126147757-d9706b10-1981-44b8-bf3b-45c958c06bb3.png)
(intended look)
![image](https://user-images.githubusercontent.com/15717384/126147991-33b939ea-6790-48e4-9633-0479c6075218.png)

**Comment by PalaNolho** [comment]
I can say that in the most recent versions of both modules, there are more problems. In particular:

- the sheet no longer renders the extended version in 2 columns (and it should). Instead is it will show on a single column with scrolling.
![image](https://user-images.githubusercontent.com/6009914/156754820-cd004df5-f145-42e5-82b2-3017694403a5.png)

- The settings cog is out of place and not accessible (it's worsh when using compact more)
