### ISSUE TITLE
Lost Volume control sliders

### ISSUE THREAD

**Issue by subatoiWolf** [ernieayala/ernies-modern-layout#132]
I love your module it provides such a clean look and i use it for all my games.  I noticed that i recently lost the volume sliders and its not throwing any errors.  When i turn module offf the volume controls return

**Comment by subatoiWolf** [comment]
![Capture](https://user-images.githubusercontent.com/77259853/126919689-b2659b1d-531b-4f5c-b625-cbd994280cc5.JPG)

**Comment by ernieayala** [comment]
@subatoiWolf  What other audio mods do you have installed? Could be mod clash.

**Comment by subatoiWolf** [comment]
The only one I could think of is Blitz Soundboard.

**Comment by subatoiWolf** [comment]
When it happened i had the console open cause i was trying to troubleshoot an unrelated error. When i closed the console the controls were gone.  I hadnt added any modules and the ones i had running have worked together for a long time now.  Could i have messed something up opening and closing console to quick?

**Comment by ernieayala** [comment]
@subatoiWolf Could you get me a list of all your mods active and what game system you're on?

**Comment by PalaNolho** [comment]
I havethe same issoe. the proble seems to be the CSS `flex-direction: column`
If you remove it displayed correctly

![image](https://user-images.githubusercontent.com/6009914/127746669-3fd2d7a3-43bc-41d9-83f1-2a75839fc3a5.png)

**Comment by zeteticl** [comment]
same issue here.

**Comment by ernieayala** [comment]
I for the life of me can't replicate the issue. I'm trying some things out still.

**Comment by ernieayala** [comment]
I'm pushing a maybe fix for this. Since I can't replicate - I'm shootin in the dark. Gonna leave this ticket open until validated.

**Comment by ernieayala** [comment]
I've tested in Chrome and Firefox on Windows 10 and Chrome and Firefox OSX. Latest browsers respectively. With a ton of mods turned on that are listed in my README.md.

**Comment by PalaNolho** [comment]
Just wanted to let you know that I just tested it with the new update and the controls are back in place 👍 
I tested with a very basic world (just a few modules) and with a complex one (around 80 modules) and seems to work fine.

**Comment by subatoiWolf** [comment]
Awesome thanks soo much! Sorry been crazy busy Sent from Mail for Windows 10 From: PalaNolhoSent: Tuesday, August 3, 2021 3:43 AMTo: ernieayala/ernies-modern-layoutCc: subatoiWolf; MentionSubject: Re: [ernieayala/ernies-modern-layout] Lost Volume control sliders (#132) Just wanted to let you know that I just tested it with the new update and the controls are back in place 👍I tested with a very basic world (just a few modules) and with a complex one (around 80 modules) and seems to work fine.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
