### ISSUE TITLE
Incompatibility with Narrator Tools

### ISSUE THREAD

**Issue by jbblily** [ernieayala/ernies-modern-layout#137]
It ignores the style of narrator tools.
(background, font color customizable. Default: background black, color white) 

![image](https://user-images.githubusercontent.com/18694887/130046810-432db9ff-92fa-4e92-bb59-850a773e95f7.png)

**Comment by ernieayala** [comment]
The custom colors from Narrator only apply to the banner across the screen
![narrator2](https://user-images.githubusercontent.com/9342233/131225106-c862a712-3b30-4203-98ac-bb2bb95ef9e4.JPG)

Not the chat cards.
![narrator](https://user-images.githubusercontent.com/9342233/131225068-32f6cdac-a59c-48bf-b2d8-1e99de412007.JPG)
