### ISSUE TITLE
Applying Damage dialogue hidden in chat with  FVTT-Minimal-Rolling-Enhancements-DND5E module

### ISSUE THREAD

**Issue by pete284** [ernieayala/ernies-modern-layout#144]
There is a display issue with the damage box in chat when the MRE dice rolling module is installed.

Without ernies installed when damage is rolled a right click of the damage box will pop up above the card to apply damage to the selected token.

![damage pop up](https://user-images.githubusercontent.com/55640052/134331014-2848fee9-2c74-4b64-8ece-9fa5fd3e6bcb.png)

When ernies is made active the pop up up box displays below the damage card and the chat windows does not automatically scroll down. This means the damage is hidden.

![ernie damage right click](https://user-images.githubusercontent.com/55640052/134331151-c6b4fead-0462-4b38-bb4b-53651c4eca8d.png)

This requires scrolling down with the mouse wheel every time to display the damage box to apply.

![ernie scroll up for damage](https://user-images.githubusercontent.com/55640052/134331234-e585a2ab-93ac-4c67-91ec-d8938eb2c347.png)

Maybe there should be an an option to revert to the pop up appearing above the card or allow the chat windw to scroll down automatically when right clicked.

**Comment by ernieayala** [comment]
Beyond the scope of what I can do with just CSS.
