### ISSUE TITLE
[BUG] Logo is not turned off unless Ernie's Layout is enabled in settings

### ISSUE THREAD

**Issue by r-valyar** [ernieayala/ernies-modern-layout#146]
The logo is not disabled unless Ernie's Layout option is not enabled.

Is this intended design? 

![image](https://user-images.githubusercontent.com/63558984/147410635-9c0b0b03-5587-4d34-883d-a8096f67074a.png)

**Comment by ernieayala** [comment]
Yes, Ernie's Layout must be enabled to use this feature. I'm fixing Ernie's Layout currently so it works with v9.
