### ISSUE TITLE
Calendar-Weather Module Player formatting

### ISSUE THREAD

**Issue by Mattrogers13** [ernieayala/ernies-modern-layout#16]
When logged in as a Player the Calendar-Weather formatting is off. Looks perfect when logged in as the GM. Tested in Chrome. Using 0.1.7 version of the module.

<img width="292" alt="Screen Shot 2020-10-11 at 10 06 01 AM" src="https://user-images.githubusercontent.com/48500042/95680791-0881c400-0baa-11eb-9555-44b71d90db39.png">

**Comment by ernieayala** [comment]
Should look less bad in https://github.com/ernieayala/ernies-modern-layout/releases/tag/0.1.11
