### ISSUE TITLE
Savage Worlds (Game System) Compatibility

### ISSUE THREAD

**Issue by ViridiumRP** [ernieayala/ernies-modern-layout#162]
The Savage Worlds game system seems to work almost perfectly with EMUI! The only issue I've encountered are the attached screenshots of the Savage World character sheets with EMUI activated:

Character Sheet portraits appear oversized/in the wrong column. 

![ErniesSavageWorlds1](https://user-images.githubusercontent.com/110081032/181163539-d69ad7ec-b47d-46af-a309-1cb5872c77b2.png)

![ErniesSavageWorlds2](https://user-images.githubusercontent.com/110081032/181163553-846cc4ba-6963-4ba9-807b-c32c0abfec40.png)

For example, this is what the sheet appears like with no EMUI activated:
![NOEMUI](https://user-images.githubusercontent.com/110081032/181163854-ae7e2944-6bc3-43ad-9650-3ffe234d103e.png)

**Comment by ernieayala** [comment]
My mod will not longer modify Actor or Item sheets. This should be functional.
