### ISSUE TITLE
Sugestion about the Options and Reset Everything

### ISSUE THREAD

**Issue by jacksands** [ernieayala/ernies-modern-layout#163]
Hello! wonderful UI module!!

Please, could you see the possibility to add an export/import settings, especially useful with custom designs?

And please, make the Reset Everything call a warning, or something, since it came before saving, I press it mistakenly many, many times.... it is silly... but it would be a great change for me!

tks for everything!

Erich

**Comment by ernieayala** [comment]
Put on a new tab so there won't be accidents.
