### ISSUE TITLE
UI Not working with LockView 

### ISSUE THREAD

**Issue by zeteticl** [ernieayala/ernies-modern-layout#164]
When LockView flag  ExcludeSidebar is on, 
lockview will looking for ui.sidebar._element[0].offsetLeft.
But when ernies modern layout tune on, ui.sidebar._element[0].offsetLeft will turn to 0.
So LockView  will run error.
Hope it will be fix.
Thankyou!

**Comment by zeteticl** [comment]
Before
![image](https://user-images.githubusercontent.com/23254376/184086351-0af839f2-f299-4bd0-a5e4-be2aaccc8abd.png)
console.log(ui.sidebar._element[0].offsetLeft) = 9XX

After turn on Ernies UI
![image](https://user-images.githubusercontent.com/23254376/184086500-db6aa8a1-c389-4054-a914-0b8e636c327a.png)
console.log(ui.sidebar._element[0].offsetLeft) = 0

**Comment by zeteticl** [comment]
module LockView
https://github.com/CDeenen/LockView

**Comment by JavaShipped** [comment]
I can validate bug - it was included in a video I did on lock view. Behavior illustrated [here ](https://youtu.be/BdIZBF-A05Q?t=414)at 6:54 ish

**Comment by ernieayala** [comment]
@zeteticl @JavaShipped have either of you upgraded to V10? Does this happen still on v10 or is it a v9 thing? My local is on V10 right now and I'm having trouble reproducing this issue.

**Comment by JavaShipped** [comment]
@ernieayala this is on v9 only for me. I haven't upgraded to v10 yet. I can try and see if this is an issue for me on v10 later today after work. But I'm primarily using v9 still until some key modules get updated.

**Comment by zeteticl** [comment]
Work fine on V10!
So i will close this issue!
