### ISSUE TITLE
Ernies not working with Levels 

### ISSUE THREAD

**Issue by Korbl** [ernieayala/ernies-modern-layout#165]
Currently when Ernie's UI is loaded, the levels window doesn't display level names. 

This is what I expect.
![default_ui](https://user-images.githubusercontent.com/28134928/185792551-a17bbf3c-d935-49a2-a46b-ed9ef0814b82.png)

This is what I am getting.

![ernies_ui](https://user-images.githubusercontent.com/28134928/185792561-3ae5ea4d-1766-407b-8597-d364aea712e7.png)

Thanks!

**Comment by ernieayala** [comment]
Should be fixed as of 0.5.6
