### ISSUE TITLE
[BUG] NPC's and character's sheets

### ISSUE THREAD

**Issue by miusei** [ernieayala/ernies-modern-layout#170]
![image](https://user-images.githubusercontent.com/98015429/188967940-a60ce99d-d42d-45d8-8bc8-b5865d59cb73.png)

foundry v10

**Comment by ernieayala** [comment]
![Capture](https://user-images.githubusercontent.com/9342233/192184001-4291e51c-8ee6-4938-98a6-1a30cf703d95.JPG)

I can't replicate this on latest v10. This the default sheet?
