### ISSUE TITLE
[BUG] Theme's Ui dropdown menu's

### ISSUE THREAD

**Issue by miusei** [ernieayala/ernies-modern-layout#171]
Western
![image](https://user-images.githubusercontent.com/98015429/188992554-4fa69874-bb5d-446f-999f-1dd6e18dcb22.png)

foundry
![image](https://user-images.githubusercontent.com/98015429/188992627-b1a03cc1-a732-4ad8-b09e-ba1dec73a33d.png)

**Comment by miusei** [comment]
if I change the letter to white, the entire layout makes the letter invisible

**Comment by ernieayala** [comment]
This looks like a module conflict. How do you have a delete button?
![dd](https://user-images.githubusercontent.com/9342233/192184555-84a0ee5f-b944-4106-8e73-7773a6a13ad9.JPG)
