### ISSUE TITLE
Malformed module.json regarding version

### ISSUE THREAD

**Issue by mawburn** [ernieayala/ernies-modern-layout#172]
The `module.json` compatibility version is not correct. 

https://github.com/ernieayala/ernies-modern-layout/blob/master/module.json#L47-L49

```json
"compatibility": {
    "minimum": "10"
}
```

Should be:

```json
"compatibility": {
    "minimum": "XXX",
    "verified": "10"
}
```

edit: I had the API wrong, apparently they changed it. Not sure what your minimum is. 

![Screen Shot 2022-09-14 at 4 26 38 PM](https://user-images.githubusercontent.com/2829924/190256039-5f3c7c07-988e-4c67-8e44-b05ca39964ec.jpg)

**Comment by ernieayala** [comment]
Will be fixed in next release. Thanks!

**Comment by mawburn** [comment]
Thanks! 

But, hopefully #171 is an easy fix because it unfortunately makes the module unusable for most of my users. I personally don't mind it that much, but since I made this ticket I've had to disable it with all my groups because more than half of them couldn't stand it.

**Comment by mawburn** [comment]
Just chiming in, but hopefully this is an easy fix because it unfortunately makes the module unusable for most of my users. I personally don't mind it that much, but since I've had to disable it with all my groups because it made it unusable for more than half the players.

**Comment by ernieayala** [comment]
Fixed with https://github.com/ernieayala/ernies-modern-layout/releases/tag/0.5.1
