### ISSUE TITLE
V10 - combat tracker looks wrong when popped out

### ISSUE THREAD

**Issue by oestred** [ernieayala/ernies-modern-layout#173]
Hello. On V10, the combat tracker looks wrong. It does not have the little bar in it that advances to show who is currently up, it also does not have quite right spacing and parts seem less clear. The little circles aren't showing either.

<img width="191" alt="image" src="https://user-images.githubusercontent.com/74035873/190885135-ce8bfb22-b00b-4056-a1b8-4ae4ac646737.png">

**Comment by ernieayala** [comment]
@oestred 

![screen](https://user-images.githubusercontent.com/9342233/192185881-2ea82d7c-6e10-4ee5-8fc4-d5b076870da0.JPG)

This is a mod conflict 100%. All I have installed on my end is Foundry V10, DND5e and my mod. If you can help me narrow down the module I can help fix it.

**Comment by oestred** [comment]
I am testing it with the same thing - V10.286, DND 5e 2.0.3, and only this module.

I think I forgot to mention that in the combat tab it looks fine but when you right click the tab to pop it out that is when it looks like that. I think most people play with the comabt tab popped out so they can see the chats with rolls and that at the same time.

Left is the popped out combat tracker and right is it still on the tabs. I appreciate your looking at this.

![left and right](https://user-images.githubusercontent.com/74035873/192399912-9d80e183-6c82-444d-a5c9-cd9767cb985b.jpg)

**Comment by weepingminotaur** [comment]
Definitely a significant issue, as I prefer to keep the combat tracker popped out during combat. When popped out, the active token isn't highlighted and all the status effects are gray and hard to see.

**Comment by ernieayala** [comment]
Fixed with https://github.com/ernieayala/ernies-modern-layout/releases/tag/0.5.1

**Comment by oestred** [comment]
Thank you for the updates! Looks good on my test foundry instance. Will update my actual foundry next.
