### ISSUE TITLE
Context menu option visibility

### ISSUE THREAD

**Issue by weepingminotaur** [ernieayala/ernies-modern-layout#177]
When using Ernie's non-dark UI options (Foundry, Western, etc.), context menu options are not visible against the background unless you scroll over them. Screenshot attached.
<img width="448" alt="Screen Shot 2022-10-04 at 6 00 05 PM" src="https://user-images.githubusercontent.com/90105219/193938566-d5293b3f-5a70-4053-a8df-b731faad6951.png">

**Comment by ernieayala** [comment]
@weepingminotaur What system are you using?

DND5e and just my mod installed I can't replicate that.

**Comment by weepingminotaur** [comment]
Used Find the Culprit to find the problem! It's Monk's Little Details, specifically, the "Change Window Styles" option. Deselecting that option fixed the issue. Thanks for checking!
