### ISSUE TITLE
Module breaks or is incompatible with multiple popular modules since update.

### ISSUE THREAD

**Issue by chrisengel3** [ernieayala/ernies-modern-layout#191]
Since the update, the UI is stepping on the toes of multiple modules. Tidy5e sheet no longer works in popout, Moulinette no longer is even visible without popping it out. The update definitely seems to reach way out past where it should or is overwriting things it shouldn't.

**Comment by ernieayala** [comment]
https://github.com/ernieayala/ernies-modern-layout/issues/194
