### ISSUE TITLE
No longer works with pf2

### ISSUE THREAD

**Issue by mistamichal** [ernieayala/ernies-modern-layout#20]
Title says it all. No longer works with Pathfinder 2.

**Comment by mistamichal** [comment]
Update. It turns out that the module won't load on the forge version because the version number wasn't increased when you repackaged it and the forge doesn't recognise it as a new version, so won't load it. So, you need to increase the version number.
Cheers

**Comment by ernieayala** [comment]
I'll investigate. I see the current versions numbers are up to date in module.json. I'll test it out.

**Comment by ernieayala** [comment]
Should be updated in https://github.com/ernieayala/ernies-modern-layout/releases/tag/0.1.11
