### ISSUE TITLE
DND 5e - unchangeable color miss match in dark mode theme

### ISSUE THREAD

**Issue by JKazimiers** [ernieayala/ernies-modern-layout#201]
This only tested in FoundryVTT v10.291 and Ernie's Modern UI v0.5.5 with the System DnD5e v2.1.1.

You can't change the color for the background box of linked entries in descriptions. For example The description vor the spell `Charm Person` can create the status effect `Charmed`. There is an separated description for this effect, so the word `charmed` in the description is highlighted with a grey box. This color makes is difficult to read a light text color. 
![image](https://user-images.githubusercontent.com/85989703/215582932-27360649-b20a-4dc8-9b0a-8cb2a3683548.png)
![image](https://user-images.githubusercontent.com/85989703/215583034-5431eb72-a34a-4d88-94ed-3f6079e52e88.png)
![image](https://user-images.githubusercontent.com/85989703/215583074-20cedecb-f509-4807-9de6-1df58197a044.png)
The same problem can be seen with the preset themes `Dark Mode`, `Alien` and `Cyberpunk`.

**Comment by teo-cay** [comment]
I'm having the same issue, tried with the Simple Worldbuilding System and it is present as well

**Comment by ernieayala** [comment]
This issue should be resolved with the latest build. Items and Character sheets will have their default backgrounds from their respective system.
