### ISSUE TITLE
cropped pictures on character sheets

### ISSUE THREAD

**Issue by HobbsEnd** [ernieayala/ernies-modern-layout#202]
Love the mod. Livens the game up. Last night, I updated it. But it's cropping the squares of the character sheets to a thin 16x9. What's the procedure to put them back to their full square glory, or was that an unintentional glitch in the upgrade code? Thanks again for the mod..!
<img width="333" alt="Screenshot 2023-02-12 at 8 35 40 AM" src="https://user-images.githubusercontent.com/125208239/218324915-71c9488c-1bb7-48a4-b046-c86f7218eb05.png">
<img width="296" alt="Screenshot 2023-02-12 at 8 35 30 AM" src="https://user-images.githubusercontent.com/125208239/218324918-98c57e1b-a4ee-4a6c-a8c5-b932522bb4e5.png">

**Comment by ernieayala** [comment]
@HobbsEnd What System is that in?

**Comment by HobbsEnd** [comment]
OpenD6 Space

**Comment by Iankid** [comment]
getting the same in Starfinder
![image](https://user-images.githubusercontent.com/60759323/218342961-c9cd6db0-0384-497f-8ba3-dbfa43d900ac.png)

**Comment by ernieayala** [comment]
@HobbsEnd @Iankid 
I made an update in a pre-release that should fix this. I don't have time to make another full release so this will have to be a work around if you want to use it. 

https://github.com/ernieayala/ernies-modern-layout#pre-release-url-use-at-your-own-risk

**Comment by HobbsEnd** [comment]
Thanks for doing this..!

**Comment by Iankid** [comment]
Ya, works. Thank you.
On a connected note, but less crucial. there's a similar effect for the Starfinder logo in the top left.
![image](https://user-images.githubusercontent.com/60759323/218564845-0ea49bf6-1f30-4139-b49b-6b2c0b161f1e.png)
Don't mind the module making it smaller, but maybe not squished.

**Comment by Iankid** [comment]
welp, least on the pre-release build, it's making NPC images take up their whole sheet.
![image](https://user-images.githubusercontent.com/60759323/218862135-fcd7c8b5-7117-4c01-97ee-7ef120ec8aaf.png)

**Comment by ernieayala** [comment]
Should be updated with latest release.
