### ISSUE TITLE
Display error in fxmaster

### ISSUE THREAD

**Issue by zeteticl** [ernieayala/ernies-modern-layout#204]
In Foundry color theme, fxmaster which look like this.

![image](https://user-images.githubusercontent.com/23254376/219555816-88a6721f-610a-4bd5-b886-727a0e3a0716.png)

**Comment by ernieayala** [comment]
They keep changing their markup. I'm just going to make sure the text shows up, not going to do more until they settle down on markup changes.

**Comment by ernieayala** [comment]
Should be updated with latest release.
