### ISSUE TITLE
Text Selection Invisible with Dark Background

### ISSUE THREAD

**Issue by ThePoetics** [ernieayala/ernies-modern-layout#206]
When using a dark background (see attached theme file), it is nearly impossible to tell what text is being highlighted by a mouse. I didn't see a "highlight color" or similar in the theme settings, but it would be a very nice addition. Thank you!

Tested using both Firefox and Edge

Example:
![image](https://user-images.githubusercontent.com/87587068/226057325-22b1a448-a551-4659-8970-e4b7fd4c4dac.png)
Setting File: [ernieTheme.json.txt](https://github.com/ernieayala/ernies-modern-layout/files/11006572/ernieTheme.json.txt)

**Comment by ernieayala** [comment]
What version are you on? I just made an update to 0.5.7 2 days ago to remove the black highlight.

https://github.com/ernieayala/ernies-modern-layout/commit/6495e0a847f04de9c0c71469bebcc424a5bf7f42#diff-9d10f510966014a626d83ab288be65e0d282756605e8b8fdf69ec0b1ae149ba8L117

**Comment by ThePoetics** [comment]
You sneaky devil! I had run an update just shy of a week ago and hadn't checked again.

Resolved, thank you!
