### ISSUE TITLE
[Feature request] Add multilanguage support

### ISSUE THREAD

**Issue by lozalojo** [ernieayala/ernies-modern-layout#21]
Please add the framework for translating the module to other languages (as other modules do, with an en.json file in a lang folder with keys that we can translate).
I have translated more than 10 modules and this one doesnt support translating.
Thanks and great work!

**Comment by ernieayala** [comment]
Okie dokie. I can add this.

**Comment by ernieayala** [comment]
Added in https://github.com/ernieayala/ernies-modern-layout/releases/tag/0.1.11
