### ISSUE TITLE
[Bug] Call of Cthulhu/HavlockV

### ISSUE THREAD

**Issue by lozalojo** [ernieayala/ernies-modern-layout#23]
Hi:

In Savage Worlds, works ok:
![](https://i.ibb.co/47zHFzT/screenshot-107.jpg)
In Call of Cthulhu/HavlockV, macro bar is not shown correctly, the macro line switcher is at the bottom, not seen in the layout:
![](https://i.ibb.co/P4yY7kB/screenshot-106.jpg)

Both tested on 0.7.6, _no_ modules loaded except Ernies Modern Layout

HavlockV:
https://github.com/HavlockV/CoC7-FoundryVTT

**Comment by ernieayala** [comment]
Should be fixed in https://github.com/ernieayala/ernies-modern-layout/releases/tag/0.1.11
