### ISSUE TITLE
Suggestion: Whetstone Compatibility

### ISSUE THREAD

**Issue by akrigline** [ernieayala/ernies-modern-layout#26]
[Whetstone](https://github.com/MajorVictory/Whetstone) is attempting to make it simple for users to manage and customize UI overhauls. Recommend taking a look at porting this into that framework. The wiki is pretty well documented.

It's possible to load via Whetstone if Whetstone is already active, else DIY the loading, thereby avoiding a hard module dependency if that gives you pause.

**Comment by ernieayala** [comment]
I doubt I'll have time to do that soon but I'll defiantly take a read to see if it supports how I overhaul the UI.

**Comment by Sonny-Crockett** [comment]
I like this as well!
