### ISSUE TITLE
UI conflict with Mess (0.76)

### ISSUE THREAD

**Issue by VexxMyst** [ernieayala/ernies-modern-layout#27]
Sorry if this isn't the right repository, but after the 0.76 update it looks like Mess is conflicting in a way where it pushes the roll dropdown as well as the export and delete chat buttons off the screen; and when you click on the dropdown you get this:

![thisisamess](https://user-images.githubusercontent.com/74265604/98718666-b70d5600-235c-11eb-8f1b-8148062e6fc0.PNG)

For transparency, I'm using Dice Tray, Polyglot and Mess in addition to this module. I'm not sure how easy of a fix it would be, but the vanilla layout has Mess and the dropdown/chat buttons on a different row, and it seems to work fine in that instance.

**Comment by ernieayala** [comment]
Fixed with release 0.2.0
