### ISSUE TITLE
'Dice Tray' module will not work with this UI...

### ISSUE THREAD

**Issue by WildBillLives** [ernieayala/ernies-modern-layout#3]
Dice Tray module ( https://foundryvtt.com/packages/dice-calculator/ )  does not work with this UI. Don't now who would need to add support for it, so posting it here as a start. 

Thanks!

**Comment by ernieayala** [comment]
I'll take a look at it! :)

**Comment by ernieayala** [comment]
![dice-tray-png](https://user-images.githubusercontent.com/9342233/86543024-c7ee1c80-becf-11ea-8c24-9b7fdd12ad2c.PNG)
