### ISSUE TITLE
Borders on some elements in chat message are not using the border color.

### ISSUE THREAD

**Issue by adriangaro** [ernieayala/ernies-modern-layout#42]
As the title says, some elements have grooved borders in chat which don't respect the border color set of the theme.

![image](https://user-images.githubusercontent.com/11583810/99744231-fae02800-2adf-11eb-866a-051b03c146da.png)

To note in this case I use better rolls so maybe their roll template causes this.

From inspecting elements some of the borders are also caused by midi-qol, so support for that would be awesome.

**Comment by ernieayala** [comment]
Made some updates to - but hard to get all of em
