### ISSUE TITLE
Compact mode break character/npc sheet title bar options

### ISSUE THREAD

**Issue by Trasoer** [ernieayala/ernies-modern-layout#5]
![ermouierror](https://user-images.githubusercontent.com/67931699/86661573-227c9b00-bfec-11ea-9169-0211cecea50f.jpg)
when selecting compact mode the widgets in the title bar of character sheets became bunched up and unreadable.

**Comment by ernieayala** [comment]
@Trasoer What module do you have installed to have GM Notes show up?

**Comment by ernieayala** [comment]
Fixed with 0.0.8.
