### ISSUE TITLE
Various Compatibilities

### ISSUE THREAD

**Issue by Greysion** [ernieayala/ernies-modern-layout#54]
Hello!

I just wanted to step in and quickly thank you for your incredible mod.

It's delightful on my eyeballs and makes for a much nicer foundry experience. Thank you for that.

The current satisfaction of my eyeballs aside, I was wondering if perhaps you might look at adding functionality and compatibility for the following mods:

- [Monks Scene Navigation](https://github.com/ironmonk88/monks-scene-navigation)
  - The topbar on this one can cause some strange interactions with longer buttons.
  ![image](https://user-images.githubusercontent.com/39004735/108504137-652b8300-72f0-11eb-873a-67e1be3e33ff.png)

- [One Journal](https://gitlab.com/fvtt-modules-lab/one-journal)
  - The buttons in the Journal Entry and some of the dialogue boxes are kind of wonky.
  ![image](https://user-images.githubusercontent.com/39004735/108504342-ad4aa580-72f0-11eb-8863-ab1f83335cd4.png)

- [Forien's Quest Log](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log)
  - This one is just funny.
  ![image](https://user-images.githubusercontent.com/39004735/108504437-d23f1880-72f0-11eb-99a9-a54771ab21cb.png)

- Forgive me, for I do not know upon which module has created this blemish.
  - ![image](https://user-images.githubusercontent.com/39004735/108505479-71b0db00-72f2-11eb-97ba-2129316c883f.png)

Thank you very much for any consideration you might give to these fixes.

**Comment by ernieayala** [comment]
- overhaul to monks
- fixed one journal alignment
- removed my styling completely from quest log - mine just looks bad
- don't know
