### ISSUE TITLE
Issue with Folder Structure with the module active

### ISSUE THREAD

**Issue by meisterlix** [ernieayala/ernies-modern-layout#59]
When using the module the entire internal folder structure except for the base and handouts folders disappear. They reappear when deactivating the module

**Comment by ernieayala** [comment]
@meisterlix Can you post a screenshot and let me know if there are any other UI modules you're using?

**Comment by meisterlix** [comment]
@ernieayala I've got Combat Carousel and Dice Tray activated which change bits of the UI, though they don't seem to have an impact on this issue

With your module activated the file browser looks like this:
<img width="1789" alt="Bildschirmfoto 2021-04-18 um 10 59 38" src="https://user-images.githubusercontent.com/76969431/115140143-1a9b5e00-a036-11eb-83e7-3a499e8f69cb.png">

Without your module activated the folder structure looks like this:
<img width="1792" alt="Bildschirmfoto 2021-04-18 um 10 56 28" src="https://user-images.githubusercontent.com/76969431/115140225-841b6c80-a036-11eb-8032-d3e969a66381.png">


---
The other modules used are:


<img width="648" alt="Bildschirmfoto 2021-04-18 um 10 57 39" src="https://user-images.githubusercontent.com/76969431/115140248-ab723980-a036-11eb-9cf8-0835fa0ab5c8.png">
<img width="644" alt="Bildschirmfoto 2021-04-18 um 10 57 48" src="https://user-images.githubusercontent.com/76969431/115140250-af05c080-a036-11eb-8b15-adbdd4bb9759.png">
<img width="657" alt="Bildschirmfoto 2021-04-18 um 10 57 56" src="https://user-images.githubusercontent.com/76969431/115140253-b1681a80-a036-11eb-8bac-66f7d3b3118c.png">

This occurs using the Worlds without Number System as well as D&D 5e.
