### ISSUE TITLE
Support for the DSA5 system

### ISSUE THREAD

**Issue by elkowar** [ernieayala/ernies-modern-layout#60]
Currently this theme is practically unusable with the DSA5 system, as said system adds a lot of custom UI assets which conflict with how this plugin aims to design the UI. By removing most of the background assets from the DSA system, i was able to make it looks mostly usable - with the exception of the chat window still looking rather weird 
<details>
<summary>
Chat window after removing DSA5 background assets
</summary>
<img src="https://user-images.githubusercontent.com/5300871/115108775-92a05000-9f72-11eb-8f02-44b7de477068.png"/>
</details>
As well as there not being a nice way to make the charactersheet work - which is unsurprising.
<details>
<summary>
DSA5 charactersheet with this plugin
</summary>
<img src="https://user-images.githubusercontent.com/5300871/115108798-ae0b5b00-9f72-11eb-9e4c-57a0c9f41eb4.png"/>
</details>
I'd not expect the charactersheet to be changed completely, as that would definitely blow out of proportion. But it should be mostly trivial to make this plugin override the background-image links that the DSA5 system adds, and replace them with a simple background colors where necessary. that would be a trivial way to make this 90% great, only missing character and item sheets, which would be more difficult to do, but also are still fully usable without "fixing" them - they just look slightly out of place, which we could definitely live with.

**Comment by ernieayala** [comment]
Doesn't look fantastic but still got rid of a lot of backgrounds.
