### ISSUE TITLE
Support for Moulinette Modules

### ISSUE THREAD

**Issue by dirusulixes** [ernieayala/ernies-modern-layout#61]
Currently the Moulinette modules https://github.com/SvenWerlen/Moulinette-core don't work correctly for me when Modern UI is enabled. The Moulinette's main popup window is not rendered.

**Comment by fischecj** [comment]
I am also having issues with Moulinette interface.  The main popout window does render for me, but you cannot interface with the icons and thus cannot effectively use the module.  It is also a little "sticky" in that, with the main Moulinette icon selected, you cannot select the Basic Controls icon with a mouse click.  You have to click one of the other interface icons to "free up" the cursor, if you will.
