### ISSUE TITLE
Support for SmallTime

### ISSUE THREAD

**Issue by InfamousPlanet** [ernieayala/ernies-modern-layout#62]
Modern UI currently alters the layout of the SmallTime module making it difficult to use.
Expected Appearance: 
![Untitled](https://user-images.githubusercontent.com/83744909/117383699-42fdd600-aed9-11eb-8001-346587c4b98b.png)
Appearance with Modern UI on:
![unknown](https://user-images.githubusercontent.com/83744909/117383592-03cf8500-aed9-11eb-99e6-9ae16aa331e9.png)

**Comment by dirusulixes** [comment]
Not sure If you prefer a new issue being opened, but currently clicking on the time to expand the smalltime window to include the full date does not work properly:
![image](https://user-images.githubusercontent.com/5693623/118813720-5892d880-b8a7-11eb-9282-6df54cf17a9a.png)

it's supposed to be: 
![image](https://user-images.githubusercontent.com/5693623/118813882-7eb87880-b8a7-11eb-8b0d-9a4f93c35f93.png)

also, the window has a draggable handle at the bottom that does not work with Modern UI enabled:
https://github.com/unsoluble/smalltime/raw/main/doc/Placement.gif
