### ISSUE TITLE
[Problem] Toolbar options not accessible

### ISSUE THREAD

**Issue by PalaNolho** [ernieayala/ernies-modern-layout#63]
Hi, I'm having an issue with this here where the toolbar options are not accessible because they are dragged too low.

I understand why the options are opening next to the selected tool, but in a module tool like where we can add more and more modules that can add more menus, I feel it would be ideal for the options to appear aligned with the top of the toolbar. This way there will be plenty of space for the tool options as required.

![image](https://user-images.githubusercontent.com/6009914/117574567-9e94b300-b0d5-11eb-9e1c-78f49c6682ef.png)

**Comment by ernieayala** [comment]
Hey @PalaNolho, 
I already have a feature for this problem. 
![align-to-top](https://user-images.githubusercontent.com/9342233/117580539-3b8f2600-b0ad-11eb-9302-570cf24684c7.JPG)
