### ISSUE TITLE
[Issue/Improvement] Macro editor unreadable

### ISSUE THREAD

**Issue by miguel-pinto-prodmad** [ernieayala/ernies-modern-layout#65]
When editing a Macro, the syntax highlighter colour scheme is not appropriate for the background colour (or vice-versa).
The selecting text becomes also "invisible".

I would recommend a dark(er) background with a syntax highlighter using colours that contrast well with the bg colour.
(I would keep comments in a lighter colour of the background so that it's clear what is code what is comment).

![image](https://user-images.githubusercontent.com/15193682/117939632-2b22b980-b300-11eb-8f2a-ea6aef2d9706.png)

thanks

**Comment by ernieayala** [comment]
This is an issue I had with Furnace macro editing on.
