### ISSUE TITLE
Player permissions

### ISSUE THREAD

**Issue by bsleys** [ernieayala/ernies-modern-layout#7]
Player permission screen needs some work, checkbox don't line up.

![playerconfig](https://user-images.githubusercontent.com/105347/86866497-143b8700-c09f-11ea-9fc3-e0b251e8d2c7.png)

**Comment by ernieayala** [comment]
Yeah that looks terrible! I'll work on that.

**Comment by ernieayala** [comment]
Should look better in latest version.
