### ISSUE TITLE
No scrolling down ability with menus

### ISSUE THREAD

**Issue by JaretheBear** [ernieayala/ernies-modern-layout#72]
When going over items in the data folder, even when the screen is in pop-out, the scrollbar does not show and scrolling is not applicable. I am unsure if there is a module clash here or just Ernie's, I deactivated it and it was fixed. Just letting you know! Love the mod otherwise!

**Comment by ernieayala** [comment]
Like the file browser?
Also, are you using the app, firefox, safari, ie?

@JaretheBear

**Comment by JaretheBear** [comment]
I am using chrome. I will screenshot the issue. thank you for the rapid reply!

**Comment by JaretheBear** [comment]
![image](https://user-images.githubusercontent.com/73076268/119273011-f4d61b80-bbd6-11eb-876a-415077032989.png)
