### ISSUE TITLE
Chat issues

### ISSUE THREAD

**Issue by Iankid** [ernieayala/ernies-modern-layout#74]
Playing the SFRPG system.
I am now having a new issue where character skill and ability outputs to chat are not displaying their name or image along the result.
disabling the Modern UI removes this issue.

**Comment by ernieayala** [comment]
@Iankid can you give me a screenshot? I don't know what I'm looking for, haven't used SFRPG. :(

**Comment by Iankid** [comment]
![ChatIssue](https://user-images.githubusercontent.com/60759323/120401539-0022f880-c2f5-11eb-9d51-7618bef9a2a7.png)
First with Modern UI, 2nd without.
