### ISSUE TITLE
Cannot read property 'replace' of undefined     at setFontFamily 

### ISSUE THREAD

**Issue by p4535992** [ernieayala/ernies-modern-layout#77]
Getting this little exception on the method 'setFontFamily' with foundry 0.8.6.

![alt](https://i.imgur.com/HBg1h91.png)

**Comment by ernieayala** [comment]
@p4535992 Question for you, are you on a hosted server in the cloud or are you running locally? I'm trying to reproduce but having difficulty.

**Comment by p4535992** [comment]
A remote virtual machine on the cloud.

**Comment by ernieayala** [comment]
@p4535992 Are you still getting this error? I tried putting it behind a timeout to give the page a moment to catch up.

**Comment by p4535992** [comment]
Sadly the console error it's still there, but it's seem only me has this issue, so it must be some firewall rule or some missing font on my linux machine (i use a Redhat CentoOS 8) . I will investigate by my side and eventually close this issue.

**Comment by ernieayala** [comment]
You're not the only one. Someone else mentioned it as well. Could be security issues. I'm loading an external link in the head and I know some systems don't like it.

**Comment by ernieayala** [comment]
Does it cause the rest of the app to stop running? I could make a toggle to turn that feature off

**Comment by p4535992** [comment]
No is not a grave exception, the app seem to working fine at least from my tests.

**Comment by ernieayala** [comment]
I tried putting a few more checks in the script. Javascript is not really my thing but let me know if my changes fixed it.

**Comment by p4535992** [comment]
Solved with version 0.3.5 !!!
