### ISSUE TITLE
Support for Custom Fonts

### ISSUE THREAD

**Issue by Leppard06** [ernieayala/ernies-modern-layout#80]
I'm loving the option to use different fonts to flavor the UI according to the world's aesthetic. It would be great if we could expand on the list of fonts by using free-to-use Google Fonts. Forien's Custom Fonts already allows us to import fonts from Google Fonts to Foundry for use in drawings and journals. Any way you could add support for that? Thanks!

**Comment by ernieayala** [comment]
This one might take a while. I really don't have the technical chops for that kind of thing but maybe I'll get lucky and someone will help me out. ha

**Comment by ernieayala** [comment]
It's pretty buggy if not used correctly - but it will do the job.
