### ISSUE TITLE
Player window missing after turning off hide function

### ISSUE THREAD

**Issue by evilcj925** [ernieayala/ernies-modern-layout#81]
The player list window is missing even after turning off the hide function for it.

**Comment by ernieayala** [comment]
@evilcj925 The player window in the bottom left? Hmm... Can you check to see if there is a class called `-emu-players` on the HTML tag? That is the class that hides it.

**Comment by evilcj925** [comment]
yes it is there when i check elements view. turning it off has the player list show up, but it is hidden behind the macro bar. 
![Capture](https://user-images.githubusercontent.com/67852506/121761718-4131be80-cae6-11eb-8562-a5c4f2de200c.PNG)

**Comment by ernieayala** [comment]
You might need to reinstall the mod. I can't for the life of me replicate the issue. 
I've looked in Chrome and Firefox. What other mods do you have installed? If you have Tidy UI Game Settings you should be able to grab a quick list of it.

**Comment by evilcj925** [comment]
about-time--v0.8.5;
acelib--v1.1.2;
ActiveAuras--v0.3.03;
ATL--v0.2.14;
advanced-macros--v1.8;
adventuremusic--v1.1.0;
ambientdoors--v2.2.4;
angela-maps--v1.0.0;
atropos-maps--v1.2.1;
autocomplete-inline-properties--v2.1.1;
autocomplete-whisper--v0.3.3;
autoanimations--v0.3.72;
journal-icon-numbers--vv1.3.0;
betterCurses--v3.0.0;
betterrolls5e--v1.5.3;
betterroofs--v0.7.7;
Border-Control--v1.2.03;
boy-king-of-idaho-music-pack--v1.0.0;
CautiousGamemastersPack--v0.2.1;
character-actions-list-5e--v4.0.0;
_CodeMirror--v5.58.3-fvtt3;
combat-utility-belt--v1.5.0;
CommunityLighting--v0.4.1;
compendium-browser--v0.4.5;
compendium-folders--v2.3.2;
condition-automation--v3.0.1;
5e-training--v0.6.0;
Custom-Token-Animations--v0.2.51;
czepeku-sample-pack--v1.1.0;
darkraven-games-soundscapes-free--v1.0.1;
dndAudioBundle-HammerHome--v1.2;
ddb-importer--v2.1.7;
deprecated-modules--v1.1.3;
df-curvy-walls--v3.1.0;
dfreds-droppables--v1.2.5;
dice-so-nice--v3.4.2;
wcube--v1.0.2;
dice-calculator--v0.6.8;
dnd5e-helpers--v2.0.4;
dww-battlemaps--v1.2.1;
drgh-encounters-1--v1.5.0;
dragupload--v2.0.0;
dae--v0.8.13;
easy-target--v2.12;
ernies-modern-layout--v0.3.2;
expander--v0.0.6;
find-the-culprit--v1.3.3;
fa-dm-screen--v0.4.1;
forien-copy-environment--v2.0.4;
forien-quest-log--v0.6.0;
foundry_community_macros--v0.41;
foundry_community_tables--v0.14;
foundryvtt-arms-reach--v1.0.14;
free-loot-tavern-compendium--v1.9.1;
fxmaster--v1.0.10;
gAudioBundle-1--v2.3;
gm-notes--v0.4.1;
gm-screen--v2.6.0;
grouproll--v0.7.3;
heliana-broodmother--v1.0;
initiative-double-click--v1.0;
itemcollection--v1.8.1;
itemacro--vv1.5.1;
animated-spell-effects--v0.6.8;
animated-tokens--v0.2.2;
JB2A_DnD5e--v0.2.0;
jaamod--v0.3;
keybind-lib--v0.3.2;
koboldpressogl--v0.24;
lazymoney--v0.9.10;
lessfog--v0.8.1;
levels--v0.2.9;
colorsettings--v2.5.9;
lib-df-hotkeys--v2.3.4;
lib-find-the-path--v1.4.0;
lib-wrapper--v1.6.1.0;
lootsheetnpc5e--v3.0.3;
lordudice--v0.1;
MaterialDeck--v1.4.4;
_mathjs--v7.5.1-fvtt2;
mcromusic-sampler--v1.0.0;
mm-dungeons-and-forests-free--v1.0.5;
midi-qol--v0.8.6;
milbys-maps-free--v1.1.8;
mikwewa-free--v1.3.0;
mob-attack-tool--v0.2.4;
monks-little-details--v1.0.29;
monks-scene-navigation--v1.0.14;
monsterblock--v3.0.0;
moonlight-maps-free--v1.1.0;
multilevel-tokens--v1.5.0;
music-d20-sampler--v1.0.0;
narrator-tools--v0.56;
npcgen--v1.0.2;
NotYourTurn--v1.1.5;
one-journal--v1.4.2;
tomcartos-ostenwold--v1.1.1;
parallaxia--v0.3.2;
pdfoundry--v0.8.9;
perfect-vision--v1.9.4;
pings--v1.2.12+0.8.6;
polyglot--v1.6.6;
popout--v1.3;
popout-resizer--v1.3;
quick-encounters--v0.8.0;
quick-insert--v2.4.7;
smip-compendium--v0.5.0;
settings-extender--v1.1.5+0.8.6;
SharedCompendiums--v1.0.0;
SharedData--v1.0.4;
foundryvtt-show-notes--v0.3;
foundryvtt-simple-calendar--vv1.2.63;
skill-customization-5e--v2.3.0;
smart-doors--v1.2.7;
socketlib--v1.0.6;
_sortablejs--v1.10.2-fvtt1;
SoundBoard--v1.5.1;
SoundBoard-BlitzFreePack--v1.0.0;
SoundBoard-BlitzCommunityPack--v1.0.0;
spellarena--v1.3.0;
spellTemplateManager--v0.5.0;
split-journal--v1.1;
tabletop-music-bazaar-free--v1.0.0;
tabletop-rpg-music--v1.3.0;
tacticalmap-free--v1.1.0;
mad-cartographer-free-maps--v1.0.1;
reclusive-cartographer-maps--v1.0.0;
tidy5e-sheet--v0.5.2;
tidy-ui_game-settings--v0.1.23;
times-up--v0.8.1;
token-action-hud--v1.0.22;
token-auras--v1.11;
token-hud-wildcard--v1.2.0;
vtta-tokenizer--v3.1.4;
tokenmagic--v0.5.1;
token-mold--v2.13.0;
token-tooltip-alt--vv3.0.0;
travel-pace--v2.0.0;
trigger-happy--v0.8.6;
dd-import--v2.0.1;
VoiceActor--v0.0.9;
wall-height--v3.5.3.4;
world-anvil--v1.0.3;
zoom-pan-options--v1.6.1;

**Comment by evilcj925** [comment]
uninstalled and reinstalled. same issue. 
logged in as a player the player window shows up. looking at the elements, the difference i found was the the div for the "players' was set  with a class 'app hidden' for my GM log in, while the player one was not. I edited that in the dev tools in chrome and it player window showed back up.

**Comment by evilcj925** [comment]
upon refreshing the game, seems the change does not hold, and the box disappears again

**Comment by ernieayala** [comment]
Okay, i'll need to do some testing. Even with all the other mods off it's still happening? I noticed that the alignment is slightly off on your screenshot and could be something is messing with the spacing. 

![example-2](https://user-images.githubusercontent.com/9342233/121794557-19ae2500-cbbe-11eb-92f1-9eea2ea92e91.JPG)

vs

![example](https://user-images.githubusercontent.com/9342233/121794546-f7b4a280-cbbd-11eb-88bb-af2a3a320129.JPG)

**Comment by evilcj925** [comment]
yeah, even with every mod off it still does it. When i log in as a player the player list shows up, so it is only on my GM log in that it is missing.

**Comment by ernieayala** [comment]
@evilcj925 Okay, I did some digging last night. Few things.

Is it broken when you have Ernie's Layout toggled on?
![ernies](https://user-images.githubusercontent.com/9342233/121960557-1f6d4d00-cd1b-11eb-91c8-cc8cdb439a49.JPG)

By chance do you use the built in WebCam? I found a line of code that toggles players off.
https://youtu.be/ja88yRVQmck?t=1161
![hidden-players](https://user-images.githubusercontent.com/9342233/121960617-30b65980-cd1b-11eb-9b15-7c150f50ae1a.JPG)

I was able to replicate the bug with the WebCam players hidden and Ernie's Layout Toggled Off
![replicated](https://user-images.githubusercontent.com/9342233/121960710-52afdc00-cd1b-11eb-9484-68848bdba87c.JPG)

**Comment by evilcj925** [comment]
To answer your question, no i am not using a build in web cam. 
But after updating to 8.7 the issues as fixed it self and the players window is now showing for the GM log in.

**Comment by ernieayala** [comment]
Weird. Well glad it self resolved. :D
