### ISSUE TITLE
Corner Buttons Misaligned

### ISSUE THREAD

**Issue by tjlanza** [ernieayala/ernies-modern-layout#83]
Foundry 0.8.6, EML 0.3.2

I think the pictures say it all.

Core
![image](https://user-images.githubusercontent.com/21128724/121694919-91822f80-ca98-11eb-8846-5bb665bdb400.png)

EML
![image](https://user-images.githubusercontent.com/21128724/121694789-70214380-ca98-11eb-97ee-76912802495f.png)

**Comment by ernieayala** [comment]
Two things, did you toggle the Ernie's Layout off and on to make sure everything reset and do you have a different mod on? I use this my mod for my games and I don't see the text like that.

**Comment by tjlanza** [comment]
> Two things, did you toggle the new Ernie's Layout option off and on to make sure everything reset and do you have a different mod on? I use this my mod for my games and I don't see the text like that.

Yes on the option, no on modules - I tried it without. That said, coming back to it a few hours later, I can't reproduce it now. Maybe it was something stuck in the cache. If it happens again, I'll do some more digging. For now, I'll close this.
