### ISSUE TITLE
Compact mode - Character Sheet title bar

### ISSUE THREAD

**Issue by aestrada4355** [ernieayala/ernies-modern-layout#85]
In the new version 0.3.2 on the default character sheet and as well Tidy5e, when enabling Compact mode (which I love) title bar shifts all ... "settings/icons" to the far right overlapping one another.

Default 5e - Compact enabled
![image](https://user-images.githubusercontent.com/67869538/121750220-f90c9f00-cad9-11eb-9e7c-d65b0d4d3b43.png)

Default 5e - Compact disabled
![image](https://user-images.githubusercontent.com/67869538/121750276-1477aa00-cada-11eb-8af6-adf900fcdeee.png)

Overall, loving the new overhaul.

**Comment by ernieayala** [comment]
Holy moly

**Comment by ernieayala** [comment]
I'll get a fix in today for that
