### ISSUE TITLE
Compatibility with Simple Calendar

### ISSUE THREAD

**Issue by dirusulixes** [ernieayala/ernies-modern-layout#86]
Foundry: 0.8.6
no other modules loaded (in case it matters)
Ernie's Layout: on
Compact mode: off

the save settings button in the Simple Calendar config pop-out window is bang in the middle instead of at the bottom
![image](https://user-images.githubusercontent.com/5693623/121774407-3f193f80-cb7a-11eb-820d-9ec48cb5c385.png)

**Comment by ernieayala** [comment]
Probably a `position: absolute` gone wrong. I'll take a look when I'm back in town tomorrow.
