### ISSUE TITLE
Weird Formatting on Map Navigation

### ISSUE THREAD

**Issue by corndog-foundry** [ernieayala/ernies-modern-layout#89]
I'm currently running Pathfinder 2e and using the UI. However, map navigations seem to display like this

![image](https://user-images.githubusercontent.com/76656835/121894720-5ccfdb80-cd17-11eb-8057-47ce50c3e163.png)
![image](https://user-images.githubusercontent.com/76656835/121894823-7d983100-cd17-11eb-95b2-c0ff63ba6527.png)

**Comment by ernieayala** [comment]
I have a fix for it but that fancy border will be gone. They use border backgrounds and just throws off the whole layout.
