### ISSUE TITLE
Macro text overflows from text field

### ISSUE THREAD

**Issue by RedReign** [ernieayala/ernies-modern-layout#9]
FVTT 0.6.5, module version 0.1.0
![](https://i.imgur.com/U7O65yx.png)
Disabling the module fixes this overflow. Obviously not a functionality issue, but looks a bit strange.

**Comment by ernieayala** [comment]
@RedReign This should be fixed in 0.1.1 now. I tested it in default Foundry macros and then with Furnace macros enabled. If the problem persists can you let me know what other modules you are using?

**Comment by ernieayala** [comment]
z-index issue should be fixed
