### ISSUE TITLE
No Color Applies to Text Fields in Edit Mode

### ISSUE THREAD

**Issue by tjlanza** [ernieayala/ernies-modern-layout#90]
None of the available color options appear to apply to the text of Journal Entries and other fields while in edit mode. This isn't a problem for many color schemes, but does present an issue for attempts to do do a *really* dark Dark-Mode-like color scheme.

Journal in View Mode, using Dark Mode color scheme.
![image](https://user-images.githubusercontent.com/21128724/121916219-f2607080-cd01-11eb-88c3-ac70e22d688f.png)

Journal in Edit Mode, using Dark Mode color scheme.
![image](https://user-images.githubusercontent.com/21128724/121916324-086e3100-cd02-11eb-9039-b9f44ee46518.png)

Journal in View Mode, using a more extreme color scheme.
![image](https://user-images.githubusercontent.com/21128724/121916642-55520780-cd02-11eb-8839-16f73e3ff0c2.png)

Journal in Edit Mode, using a more extreme color scheme.
![image](https://user-images.githubusercontent.com/21128724/121916753-6f8be580-cd02-11eb-9ce0-fc17e6acb66b.png)

**Comment by ernieayala** [comment]
That text editor is in an iFrame. I can't touch the properties in there. What I'll have to do is just make the background white when in edit mode. Probably best for usability overall.

**Comment by tjlanza** [comment]
That works just fine. Thank you for being so responsive.
