### ISSUE TITLE
Incompatible with Combat Focus

### ISSUE THREAD

**Issue by tjlanza** [ernieayala/ernies-modern-layout#95]
[Combat Focus](https://github.com/Oromis/foundry-combat-focus) is a module that adds the Chat Log to the bottom of the Combat Tracker. There is a grab handle between the two elements, allowing the user to change the relative sides. With EML enabled, the grab handle is still grabbable (the mouse cursor changes) but it cannot be moved.

**Comment by ernieayala** [comment]
So the creator of the mod actually has code in there that supports my mod. It has old selectors from before my refactor that will need to be updated on their end.
