### ISSUE TITLE
Improve Shadowrun 5E Compatibility

### ISSUE THREAD

**Issue by tjlanza** [ernieayala/ernies-modern-layout#96]
When used with [Shadowrun 5E](https://github.com/smilligan93/SR5-FoundryVTT), EML has a few places that could use improvement.

In an actor sheet, EML does not adjust all the fonts on the actor sheet:
![image](https://user-images.githubusercontent.com/21128724/122566397-82116200-d015-11eb-925a-8a500ce8a97e.png)

In "Environmental Modifiers", has multiple issues:

- Selected vs. Unselected Elements.
- Word Wrapping
- Background Colors

![image](https://user-images.githubusercontent.com/21128724/122566502-96555f00-d015-11eb-8362-30fed64e03b8.png)

![image](https://user-images.githubusercontent.com/21128724/122566626-bedd5900-d015-11eb-9684-919a6a23a4c1.png)

It would be really nice if it could catch and reskin the token menu element as well.
![image](https://user-images.githubusercontent.com/21128724/122572748-0a930100-d01c-11eb-84c4-3cbba5a43d9b.png)

**Comment by ernieayala** [comment]
Any elements that lives inside of an Actor or Item sheet I do no touch the contents within for anything. Other things I can look into.

**Comment by tjlanza** [comment]
> Any elements that lives inside of an Actor or Item sheet I do no touch the contents within for anything. Other things I can look into.

I can certainly understand the reluctance to mess with an actor sheet. However, even if unintentional, there are changes to the actor sheet taking place. It strips out the background, affects some of the fonts (but not all of them), and changes the color of the grab handles in the scroll bars. It looks like anything with the typeface changed doesn't get affected by EML, but everything else does.

![image](https://user-images.githubusercontent.com/21128724/122596733-4d62d200-d038-11eb-8e3d-b78739a5c825.png)
![image](https://user-images.githubusercontent.com/21128724/122596841-784d2600-d038-11eb-9a65-cc4a6e3e89f4.png)

Ideally, the input boxes below the attributes would be affected by the border color options and the grab handles would use the primary theme color.

**Comment by ernieayala** [comment]
Can you draw an arrow to the token menu element? I guess I don't really know which part.

**Comment by tjlanza** [comment]
> Can you draw an arrow to the token menu element? I guess I don't really know which part.

The part labeled "Environ. Mod" in the last screen shot.

**Comment by ernieayala** [comment]
@tjlanza Would you be able to send me a filled Shadowrun World? I really don't know how to build out/use the system and it would help me catch the edge cases.

**Comment by tjlanza** [comment]
This should be a working world, minus the art assets.
[srm206x.zip](https://github.com/ernieayala/ernies-modern-layout/files/6694174/srm206x.zip)

**Comment by ernieayala** [comment]
@tjlanza Strange, your game says I need to update my Foundry. You're on 8.7 yeah? I'll see if I can spin up my own game and just copy the into it

**Comment by ernieayala** [comment]
@tjlanza Just wanted to give you an update on this. I'm making a pass at the sheet - it looks - meh. There are a shit ton of borders. I think with a dark background or the brushed texture in default they are not noticeable. With my OOB look they are very noticeable. Also I tried overwriting the font - it blows the layout to craziness. It looks like it was built to be very precise in it's measurements. It's not a very forgiving layout to manipulate. 
![Capture](https://user-images.githubusercontent.com/9342233/123683751-72f29700-d801-11eb-9d12-dc61f95a56cf.JPG)

**Comment by tjlanza** [comment]
Very peculiar, and unfortunate. The current version looks mostly okay with the dark background I'm using. I'd be okay with you backing out the changes and abandoning the effort. Thanks for trying, though.

There's a few minor tweaks I'd like. I'll try to see if I can pick them out via something like [Custom CSS](https://github.com/cswendrowski/FoundryVTT-Custom-CSS).

**Comment by ernieayala** [comment]
Not likely to ever get around to this. Actors and Items won't be touched anymore.
