### ISSUE TITLE
Some components seems to be a bit messed up

### ISSUE THREAD

**Issue by PalaNolho** [ernieayala/ernies-modern-layout#99]
I just updated from CORE 0.7.10 to CORE 0.8.7 and I noticed that some of the fiends are missing a proper style or their display is messed up (some examples below)

I'm experiencing this on **module v0.3.6**

![image](https://user-images.githubusercontent.com/6009914/122641858-b95c3d80-d0ff-11eb-96c1-7bfe788ee7c8.png)

![image](https://user-images.githubusercontent.com/6009914/122641900-f6c0cb00-d0ff-11eb-8a8e-a32c6dd751bd.png)

![image](https://user-images.githubusercontent.com/6009914/122641931-21128880-d100-11eb-9314-7616e6d0a48c.png)

**Comment by ernieayala** [comment]
@PalaNolho The middle screenshot - what's the issue?

**Comment by PalaNolho** [comment]
This is how it looked before.

![2F5674B7-493D-4C8A-8345-2E0DD358C000](https://user-images.githubusercontent.com/6009914/122689423-527f7700-d21a-11eb-8751-b61e7760b422.png)

based on this, it seemed that something was not right.

**Comment by ernieayala** [comment]
I adjusted the border colors and the font sizes of the inputs. Should be more readable.
